### ISSUE TITLE
Should the trigger be able to connect to multiple brokers? 

### ISSUE THREAD

**Issue by karthik2804** [spinkube/spin-mqtt-trigger-sdk#16]
Currently the trigger can only connect to one MQTT broker with the configuration being defined at the application trigger level. Does allowing each component configuration to specify overrides to connect to a different server make sense? It could be implemented similarly to how the Redis trigger implements it today and the configuration could look something like 

```toml
[application.trigger.mqtt]
address = "mqtt://localhost:1883"
username = "user"
password = "password"
keep_alive_interval = "30"

[component.mqtt-c01]
source = "target/wasm32-wasi/release/mqtt_app.wasm"
override_address =  "mqtt://mydifferentaddress:1883" # This will override the default "mqtt://localhost:1883"
# potentially have override_username, override_password override_keep_alive_interval ? 
```
